version: '3.9'

services:
  # Banco de Dados SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password1!"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - minha-rede
  
  # Executar os scripts iniciais
  sql-server-cmd:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: sql-server-cmd
    command: /bin/bash -c '/opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P Password1! -i /dbinit.sql'
    restart: on-failure
    networks:
      - minha-rede
    depends_on: 
      - sql-server

  # API .NET 6.0
  web-api:
    build:
      context: ./backend/CadastroAPI/CadastroAPI
      dockerfile: Dockerfile
    container_name: cadastro-web-api
    ports:
      - "5047:80"
    volumes:
      - apivolume:/var/opt/api
    networks:
      - minha-rede
    depends_on: 
      - sql-server

  # Aplicação Angular 16
  angular-app:
    build:
      context: ./frontend/CadastroWeb
      dockerfile: Dockerfile
    container_name: cadastro-web-app
    ports:
      - "4200:80"
    networks:
      - minha-rede

volumes:
  sqlvolume:
  apivolume:

networks:
  minha-rede:
    driver: bridge
